FROM python:3.10-slim
RUN apt-get update && apt-get install -y build-essential libssl-dev libffi-dev python3-dev && rm -rf /var/lib/apt/lists/*
RUN pip install opencanary
ENTRYPOINT ["opencanaryd", "--foreground"]
